@startuml ClassDiagram

object AAA
object ChessGame
object board
object player
object spots
object coordinate
object pieces
object rook
object bishop
object knight
object queen
object king
object pawn
object turns

object turnGoals
object checkMovements
object receiveInputs

object piecesGoals
object detailStepApproach
object name
object isWhite
object location
object isDead

object playerGoals
object provideInputs
object initializePieces

object spotGoals
object moveRemovePiece

object boardGoals
object printBoard
object updateBoard

object gameGoals
object startGame
object createBoard
object createPlayers


ChessGame *-- player
ChessGame *--> turns
ChessGame o-- gameGoals
ChessGame *-- board

player o-- playerGoals
player o-- pieces

playerGoals <|-- provideInputs
playerGoals <|--initializePieces

board o-- boardGoals
board *-- spots
boardGoals <|-- printBoard
boardGoals <|-- updateBoard

spots *--> pieces
spots *-- coordinate
spots <|-- spotGoals
spotGoals <|-- moveRemovePiece

gameGoals <|-- createBoard
gameGoals <|-- startGame
gameGoals <|-- createPlayers

turns o-- turnGoals
turnGoals <|-- checkMovements
turnGoals <|-- receiveInputs

pieces *-- name
pieces *-- isWhite
pieces *-- location
pieces *-- isDead

pieces <|-- rook
pieces <|-- bishop
pieces <|-- knight
pieces <|-- queen
pieces <|-- king
pieces <|-- pawn

board <-- turns
board --> player

pieces o-- piecesGoals
piecesGoals <|-- detailStepApproach

@enduml